name: CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - run: pip install -r backend/requirements.txt
      
      - name: Create .env file
        run: |
          echo "DB_USER=admin" > backend/.env
          echo "DB_PASSWORD=admin" >> backend/.env
          echo "DB_NAME=twitter" >> backend/.env
      
      - run: black --diff --check backend/app/
      
      - run: flake8 --config=backend/app/config_data/.flake8 backend/app/
      
      - run: pytest backend/tests/
      
      - run: mypy backend/app/ --ignore-missing-imports
